### ISSUE TITLE
ImportError: No module named 'bbcore'

### ISSUE THREAD

**Issue by muranava** [magnusnissel/birdbody#1]
hi getting this error when trying to run birdbody.py

**Comment by magnusnissel** [comment]
Which file were you running? I am still figuring out how do deal with pypi and packaging. It works for me when I either run birdbody.py from the root directory or **main**.py from the folder (the latter will be renamed next update as it seems to cause problems with pyinstaller)

**Comment by muranava** [comment]
i think may be am trying to run python3 with system that has python2 as default
i was running birdbody.py from root; tried with main but getting missing module error for tweepy

**Comment by magnusnissel** [comment]
Yeah, tweepy is a dependency of birdbody. It's a library to access the Twitter API with. If you install birdbody via pip (and I think also easy_install) it should be installed automatically as well. If not you need to install Tweepy by hand (e.g. via pip or from GitHub: https://github.com/tweepy/tweepy).

Most *nix systems come with Python 2 preinstalled, but it's generally no problem installing Python 3 (much better with unicode) next to it and then run Python 3 scripts with the "python3" command instead of just "python".
